### ISSUE TITLE
Enable wiki

### ISSUE THREAD

**Issue by SatanicMechanic** [jliuhtonen/blu-hawaii#14]
Would you mind enabling the wiki for this project? I’m trying to get the container running on Synology, with or without portainer, and thought I might get some help if I document my progress.

**Comment by jliuhtonen** [comment]
Hi @SatanicMechanic! Thanks for your interest in the project and your request. And sorry for the belated response.

At this stage I'd like to keep things as simple as possible so everything would be stored just in the same Git repository. Would it be possible for you to add your instructions to the repo as a markdown file? Something like `docs/synology.md`. You can still use the GitHub editor if you prefer. Also, feel free to ask me any questions you might have regarding running in container. Thanks!

**Comment by SatanicMechanic** [comment]
No problems.  I didn't make much progress so I'm thinking of offering a bounty for generation of a native DSM package, which is preferred over a container on the low end NAS units.  To do that I would need to create an issue, then link to it on algora.  Would that be ok?

**Comment by jliuhtonen** [comment]
> To do that I would need to create an issue, then link to it on algora.  Would that be ok?

Yeah, of course!

For running you need Node 20, Last.fm API keys and configuration in env variables. When running in container you will also need some volumes as described in the docs.

Would it be ok if I close this issue then?
