### ISSUE TITLE
Pandora Station Scrobbling

### ISSUE THREAD

**Issue by zquestz** [jliuhtonen/blu-hawaii#85]
When scrobbling my Pandora stations, it sets the song to "Band-Name Radio", instead of the track that actually played!

You can see this on my LastFM feed.

https://www.last.fm/user/zquestz

Also, seeing a few duplicates. We have 8 BluOS Nodes in the house, and we link rooms together. Probably a larger setup than most users.

This app is awesome and other scrobbles seem to be perfect, would love to get this little issue fixed!

**Comment by jliuhtonen** [comment]
Thank you for taking the time to write this issue and for your valuable feedback. Since Pandora is not available where I live, would you be able to provide a sample output of what a Node gives as its status when you are playing a Pandora radio?

You can query a player with an IP like this on macOS or Linux using curl (or Postman or which tool you prefer):
`curl http://<player_ip>:11000/Status`

If you could provide the XML output that you get, it would help me fix the issue as the documentation is a bit vague on this particular case.

Regarding the duplicates from many players: It might be that in a setup like yours the players will each report when they are done playing a track. Am I correct that you are seeing as many scrobbles per track as there are players in a given room / group?

**Comment by jliuhtonen** [comment]
There seems to be an issue related to the fact that because if not playing, say files from a network drive, but streaming from a streaming service the `name` attribute is not available so blu-hawaii uses `title1`. However, when streaming certain network radios, like Radio Paradise, the `title1` field will include the name of the stream/station, not the track playing. I suspect that this is the case with Pandora too.

Example, Radio Paradise:
```
...
<album>Things are changing</album>
<artist>Gone Gone Beyond</artist>
...
<title1>RP Main Mix</title1>
<title2>Things are changing</title2>
<title3>Gone Gone Beyond • Things are changing</title3>
```

Playing from a file on network drive:
```
...
<album>Faded Caprice</album>
<artist>E.R.P.</artist>
...
<name>Let's Amble</name>
...
<title1>Let's Amble</title1>
<title2>E.R.P.</title2>
<title3>Faded Caprice</title3>
```

Streaming from Tidal:
```
...
<album>Imaginal Disk</album>
<artist>Magdalena Bay</artist>
...
<title1>She Looked Like Me!</title1>
<title2>Magdalena Bay</title2>
<title3>Imaginal Disk</title3>
```
It would be possible to use the service id, but that would be brittle as services might get added or renamed. Let's see the Pandora output as well to be able to determine if some simple rule could be used to determine which title to use.

Like, if `title2` matches the artist and `title3` the album, use `title1`, else use `title2`. Too bad that the API does not return better data here.

**Comment by zquestz** [comment]
I am out of town for a couple days, but will get you that sample XML output as soon as I get home. 😀-JoshOn Sep 12, 2024 11:36 PM, Janne Liuhtonen ***@***.***> wrote:
Thank you for taking the time to write this issue and for your valuable feedback. Since Pandora is not available where I live, would you be able to provide a sample output of what a Node gives as its status when you are playing a Pandora radio?
You can query a player with an IP like this on macOS or Linux using curl (or Postman or which tool you prefer):
curl http://<player_ip>:11000/Status
If you could provide the XML output that you get, it would help me fix the issue as the documentation is a bit vague on this particular case.
Regarding the duplicates from many players: It might be that in a setup like yours the players will each report when they are done playing a track. Am I correct that you are seeing as many scrobbles per track as there are players in a given room / group?

**Comment by zquestz** [comment]
Here is the sample output XML.

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<status etag="8140fd864cae756060b386cafe4e4258">
<actions>
  <action hide="1" name="back" />
  <action name="skip" url="/Action?service=Pandora&amp;skip=TR%3A2166321" />
  <action icon="/images/loveban/love.png" name="love" notification="Pandora will play more tracks with similar music qualities." state="-1" text="Love" type="thumbs" url="/Action?service=Pandora&amp;love=TR%3A2166321" />
  <action icon="/images/loveban/ban.png" name="ban" notification="This track won't play on this station." state="-1" text="Ban" type="thumbs" url="/Action?service=Pandora&amp;ban=TR%3A2166321" />
</actions>
<album>Prana Pulse</album>
<albumid>AL:191326</albumid>
<artist>Shaman's Dream</artist>
<artistid>AR:213207</artistid>
<canMovePlayback>true</canMovePlayback>
<currentImage>https://content-images.p-cdn.com/images/11/92/78/b5/01bd4f0bbf2e3324fe8a6577/_640W_640H.jpg</currentImage>
<cursor>0</cursor>
<db>-28.5</db>
<image>https://content-images.p-cdn.com/images/11/92/78/b5/01bd4f0bbf2e3324fe8a6577/_640W_640H.jpg</image>
<indexing>0</indexing>
<mid>15</mid>
<mode>1</mode>
<mute>0</mute>
<pid>10</pid>
<prid>0</prid>
<quality>191000</quality>
<repeat>0</repeat>
<schemaVersion>34</schemaVersion>
<service>Pandora</service>
<serviceIcon>/Sources/images/PandoraIcon.png</serviceIcon>
<serviceName>Pandora</serviceName>
<shuffle>0</shuffle>
<sid>140</sid>
<similarstationid>Pandora:radio:SF:16722:213207</similarstationid>
<sleep></sleep>
<song>0</song>
<state>stream</state>
<stationImage>https://content-images.p-cdn.com/images/3f/bd/73/31/cd7f42cba6358625dd80d56a/_500W_500H.jpg</stationImage>
<streamFormat>MP3 191 kb/s</streamFormat>
<streamUrl>Pandora:radio:ST:0:138214111317067420</streamUrl>
<syncStat>190</syncStat>
<title1>Shaman's Dream Radio</title1>
<title2>Nectar</title2>
<title3>Shaman's Dream • Prana Pulse</title3>
<totlen>445</totlen>
<trackstationid>Pandora:radio:SF:21586:2166321</trackstationid>
<volume>36</volume>
<secs>183</secs>
</status>
```

**Comment by zquestz** [comment]
Also, Spotify has some odd output.

Here's the XML

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<status etag="45b2420cb661a754d1e9c24bfe99c5d0">
<actions>
  <action androidAction="android.intent.action.VIEW" androidPackage="com.spotify.music" desktopApp="spotify:open" desktopInstall="https://spotify.com/download" icon="/Sources/images/SpotifyIcon.png" iosApp="spotify:open" itunesUrl="https://itunes.apple.com/ex/app/spotify/id324684580" name="contextMenuItem" text="Open Spotify app" />
  <action name="back" />
  <action hide="1" name="skip" />
</actions>
<album>Echoes of Silence</album>
<artist>Jane Winther</artist>
<canSeek>0</canSeek>
<currentImage>https://i.scdn.co/image/ab67616d0000b273f67bb0f29db21239ad72580b</currentImage>
<cursor>0</cursor>
<db>-40.4</db>
<image>https://i.scdn.co/image/ab67616d0000b273f67bb0f29db21239ad72580b</image>
<indexing>0</indexing>
<inputId>Spotify</inputId>
<mid>15</mid>
<mode>1</mode>
<mute>0</mute>
<noCoverBackground>true</noCoverBackground>
<pid>2</pid>
<prid>0</prid>
<repeat>0</repeat>
<service>Spotify</service>
<serviceIcon>/Sources/images/SpotifyIcon.png</serviceIcon>
<serviceName>Spotify</serviceName>
<shuffle>0</shuffle>
<sid>144</sid>
<sleep></sleep>
<song>0</song>
<state>pause</state>
<stationImage>/Sources/images/SpotifyIcon.png</stationImage>
<streamUrl>Spotify:</streamUrl>
<syncStat>63</syncStat>
<title1>Spotify - playing elsewhere</title1>
<title2>Echoes of Silence</title2>
<title3>Jane Winther • Echoes of Silence</title3>
<totlen>274.377</totlen>
<volume>19</volume>
<secs>0</secs>
</status>
```

title1 comes in as a very odd value... "Spotify - playing elsewhere"
title2 is the album - Echoes of Silence
title3 is the artist and album - Jane Winther • Echoes of Silence

I don't see the actual track name at all.... =\

Not sure how best to fix this one.

**Comment by zquestz** [comment]
Spotify has some odd edge case too.

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<status etag="45b2420cb661a754d1e9c24bfe99c5d0">
<actions>
  <action androidAction="android.intent.action.VIEW" androidPackage="com.spotify.music" desktopApp="spotify:open" desktopInstall="https://spotify.com/download" icon="/Sources/images/SpotifyIcon.png" iosApp="spotify:open" itunesUrl="https://itunes.apple.com/ex/app/spotify/id324684580" name="contextMenuItem" text="Open Spotify app" />
  <action name="back" />
  <action hide="1" name="skip" />
</actions>
<album>Echoes of Silence</album>
<artist>Jane Winther</artist>
<canSeek>0</canSeek>
<currentImage>https://i.scdn.co/image/ab67616d0000b273f67bb0f29db21239ad72580b</currentImage>
<cursor>0</cursor>
<db>-40.4</db>
<image>https://i.scdn.co/image/ab67616d0000b273f67bb0f29db21239ad72580b</image>
<indexing>0</indexing>
<inputId>Spotify</inputId>
<mid>15</mid>
<mode>1</mode>
<mute>0</mute>
<noCoverBackground>true</noCoverBackground>
<pid>2</pid>
<prid>0</prid>
<repeat>0</repeat>
<service>Spotify</service>
<serviceIcon>/Sources/images/SpotifyIcon.png</serviceIcon>
<serviceName>Spotify</serviceName>
<shuffle>0</shuffle>
<sid>144</sid>
<sleep></sleep>
<song>0</song>
<state>pause</state>
<stationImage>/Sources/images/SpotifyIcon.png</stationImage>
<streamUrl>Spotify:</streamUrl>
<syncStat>63</syncStat>
<title1>Spotify - playing elsewhere</title1>
<title2>Echoes of Silence</title2>
<title3>Jane Winther • Echoes of Silence</title3>
<totlen>274.377</totlen>
<volume>19</volume>
<secs>0</secs>
</status>
```

title1 comes in as a very odd value - Spotify - playing elsewhere

That being said I don't see it scrobbling this value.

**Comment by jliuhtonen** [comment]
> Spotify has some odd edge case too.
> title1 comes in as a very odd value - Spotify - playing elsewhere
> 
> 
> 
> That being said I don't see it scrobbling this value.

This is because the state value is "pause", only statuses with state "stream" and "play" are processed.

**Comment by zquestz** [comment]
Excellent, thx =)

**Comment by jliuhtonen** [comment]
Thank you! Looks like the logic in the PR should work. I'll add a test case with that Pandora XML, fix the track comparison and release a new version. I'll let you know when I'm done. Let's keep the issue open until we can confirm that it works.

**Comment by jliuhtonen** [comment]
I've also thought about the duplicates from many players problem, let's open another issue about that one? It requires a bit more investigation and the fix is not as simple as this one. 🧐

**Comment by zquestz** [comment]
I think it might be okay. I was restarting blu-hawaii and want to do more testing on my end before I open an official ticket. =)

**Comment by jliuhtonen** [comment]
> I think it might be okay. I was restarting blu-hawaii and want to do more testing on my end before I open an official ticket. =)

That would be much appreciated. 👍 Also any logs you could share (run with `LOG_LEVEL=debug`) would be really useful. Remember to redact any information that you'd prefer not to share like IPs though.

**Comment by jliuhtonen** [comment]
I merged #87 and released v1.2.0 that fixes this. 🚀

**Comment by zquestz** [comment]
Can confirm the fix works! My scrobbles are looking legit!

**Comment by jliuhtonen** [comment]
Great! I'm closing this issue, let's continue in another one.
